export interface DifficultyLevel {
  level: number
  skillLevel: number
  movetime: number
  depth: number
  label: string
  description: string
  elo: number
}

export const DIFFICULTY_LEVELS: DifficultyLevel[] = [
  {
    level: 1,
    skillLevel: 0,
    movetime: 50,
    depth: 1,
    label: 'Новичок',
    description: 'Случайные ходы',
    elo: 400,
  },
  {
    level: 2,
    skillLevel: 1,
    movetime: 75,
    depth: 1,
    label: 'Новичок',
    description: 'Очень слабая игра',
    elo: 600,
  },
  {
    level: 3,
    skillLevel: 2,
    movetime: 100,
    depth: 2,
    label: 'Начинающий',
    description: 'Базовые ходы',
    elo: 800,
  },
  {
    level: 4,
    skillLevel: 3,
    movetime: 150,
    depth: 2,
    label: 'Начинающий',
    description: 'Простая тактика',
    elo: 900,
  },
  {
    level: 5,
    skillLevel: 4,
    movetime: 200,
    depth: 3,
    label: 'Любитель',
    description: 'Базовые комбинации',
    elo: 1000,
  },
  {
    level: 6,
    skillLevel: 5,
    movetime: 250,
    depth: 3,
    label: 'Любитель',
    description: 'Развитие фигур',
    elo: 1100,
  },
  {
    level: 7,
    skillLevel: 6,
    movetime: 300,
    depth: 4,
    label: 'Клубный',
    description: 'Простые планы',
    elo: 1200,
  },
  {
    level: 8,
    skillLevel: 7,
    movetime: 400,
    depth: 5,
    label: 'Клубный',
    description: 'Позиционная игра',
    elo: 1350,
  },
  {
    level: 9,
    skillLevel: 8,
    movetime: 500,
    depth: 6,
    label: 'Средний',
    description: 'Тактика и позиция',
    elo: 1500,
  },
  {
    level: 10,
    skillLevel: 9,
    movetime: 600,
    depth: 7,
    label: 'Средний',
    description: 'Развитые навыки',
    elo: 1600,
  },
  {
    level: 11,
    skillLevel: 10,
    movetime: 700,
    depth: 8,
    label: 'Продвинутый',
    description: 'Твёрдая игра',
    elo: 1700,
  },
  {
    level: 12,
    skillLevel: 11,
    movetime: 800,
    depth: 9,
    label: 'Продвинутый',
    description: 'Хорошая тактика',
    elo: 1800,
  },
  {
    level: 13,
    skillLevel: 12,
    movetime: 900,
    depth: 10,
    label: 'Сильный',
    description: 'Глубокие варианты',
    elo: 1900,
  },
  {
    level: 14,
    skillLevel: 13,
    movetime: 1000,
    depth: 11,
    label: 'Сильный',
    description: 'Сложная стратегия',
    elo: 2000,
  },
  {
    level: 15,
    skillLevel: 14,
    movetime: 1200,
    depth: 12,
    label: 'Эксперт',
    description: 'Экспертный уровень',
    elo: 2100,
  },
  {
    level: 16,
    skillLevel: 15,
    movetime: 1400,
    depth: 13,
    label: 'Эксперт',
    description: 'Высокая точность',
    elo: 2200,
  },
  {
    level: 17,
    skillLevel: 16,
    movetime: 1600,
    depth: 14,
    label: 'Мастер',
    description: 'Мастерская игра',
    elo: 2300,
  },
  {
    level: 18,
    skillLevel: 17,
    movetime: 1800,
    depth: 15,
    label: 'Мастер',
    description: 'Очень глубокий анализ',
    elo: 2400,
  },
  {
    level: 19,
    skillLevel: 18,
    movetime: 2000,
    depth: 16,
    label: 'Гроссмейстер',
    description: 'Уровень гроссмейстера',
    elo: 2500,
  },
  {
    level: 20,
    skillLevel: 20,
    movetime: 3000,
    depth: 20,
    label: 'Максимум',
    description: 'Полная мощь Stockfish',
    elo: 2850,
  },
]

export const INTERVIEW_PREP: DifficultyLevel = {
  level: 10,
  skillLevel: 9,
  movetime: 800,
  depth: 8,
  label: 'Interview Prep',
  description: 'Принципиальная игра среднего уровня',
  elo: 1600,
}

export function getDifficultyLevel(level: number): DifficultyLevel {
  return DIFFICULTY_LEVELS[Math.max(0, Math.min(19, level - 1))]
}
